//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCEM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Notas = new HashSet<Notas>();
        }
    
        public int idUsuario { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string pnombre { get; set; }
        public string snombre { get; set; }
        public string appat { get; set; }
        public string apmat { get; set; }
        public string email { get; set; }
        public string fonoCelular { get; set; }
        public string fonoFijo { get; set; }
        public Nullable<int> tipoUsuario { get; set; }
        public Nullable<int> alumnoRegular { get; set; }
        public int idCarrera { get; set; }
        public int idInstitucion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public ICollection<Notas> Notas { get; set; }
    }
}
